services:
  postgres:
    image: postgres:16
    container_name: order-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: orderuser
      POSTGRES_PASSWORD: orderpass123
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: order-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: order-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    container_name: order-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander
    container_name: order-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres-data: